### ISSUE TITLE
Problem using legendastv as provider

### ISSUE THREAD

**Issue by overmindbr** [Diaoul/subliminal#1013]
I'm having issues running it with legendastv provider.
It was installed using pip3, rarfile version 4.0.
Also has unrar-free installed.

```
ERROR:subliminal.utils:Unexpected error. Provider legendastv
Traceback (most recent call last):
  File "/home/***/.local/lib/python3.7/site-packages/subliminal/core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/***/.local/lib/python3.7/site-packages/subliminal/core.py", line 66, in __getitem__
    provider = provider_manager[name].plugin(**self.provider_configs.get(name, {}))
  File "/home/***/.local/lib/python3.7/site-packages/subliminal/providers/legendastv.py", line 164, in __init__
    rarfile.custom_check([rarfile.UNRAR_TOOL], True)
AttributeError: module 'rarfile' has no attribute 'custom_check'
```

**Comment by overmindbr** [comment]
works fine with rarfile 3.1.

**Comment by eastmarch** [comment]
Replacing `rarfile.custom_check([rarfile.UNRAR_TOOL], True)` with `rarfile.tool_setup()` on "legendastv.py" solves this issue without losing functionality (when dealing with [rarfile version 4.0](https://github.com/markokr/rarfile/blob/55fe778b5207ebba48b8158d2c25d9d536ec89de/rarfile.py#L3353)). Just a suggestion.
