### PR TITLE
Limit versions of rarfile that can be used

### LINKED ISSUE #1013: Problem using legendastv as provider
I'm having issues running it with legendastv provider.
It was installed using pip3, rarfile version 4.0.
Also has unrar-free installed.

```
ERROR:subliminal.utils:Unexpected error. Provider legendastv
Traceback (most recent call last):
  File "/home/***/.local/lib/python3.7/site-packages/subliminal/core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/***/.local/lib/python3.7/site-packages/subliminal/core.py", line 66, in __getitem__
    provider = provider_manager[name].plugin(**self.provider_configs.get(name, {}))
  File "/home/***/.local/lib/python3.7/site-packages/subliminal/providers/legendastv.py", line 164, in __init__
    rarfile.custom_check([rarfile.UNRAR_TOOL], True)
AttributeError: module 'rarfile' has no attribute 'custom_check'
```

### PR DESCRIPTION
**Pull request by gene1wood**
In markokr/rarfile#70 it's reported that the `custom_check` function was removed from the rarfile pypi package. As a result the error reported in Diaoul/subliminal#1013 occurs when a version of rarfile newer than 3.1 is installed.

This fixes #1013 by limiting the range of rarfile versions.

Once the legendastv provider is changed to no longer use `custom_check` this version constraint could be removed.

### CODE REVIEW

**Comment by gene1wood** [comment]
The python 2.7 Jenkins tests are failing because of #1029 
I'm unsure why the python 3 Jenkins tests, they report
```
________________________ ERROR collecting test session _________________________

Direct construction of Pep8Item has been deprecated, please use Pep8Item.from_parent.

See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.
```

However I don't see any use of `from_parent` in the subliminal tests

**Comment by clach04** [comment]
Better solution is #1045, however the setup.py in that should be updated to require `>3.1`

**Comment by gene1wood** [comment]
This PR is waiting on someone to begin maintaining this repo (see #1046) as otherwise there's nobody to merge it.

**Comment by getzze** [comment]
legendastv Provider was removed

**Comment by gene1wood** [comment]
@getzze Do you know what commit it was removed in? It appears to still be present and using the no longer existing `custom_check` method, but I could be wrong.

https://github.com/Diaoul/subliminal/blob/f86450918501ef11e26e40eef153654c52a6d8bb/subliminal/providers/legendastv.py

**Comment by ptrcnull** [comment]
it was 4130a485481dfc893cb6dfddd6e96305aa613f00, but it's only on the `develop` branch; you'll have to wait for the new release

**Comment by getzze** [comment]
Exactly, I was trying to close old PRs, sorry for not giving more information. Thanks @ptrcnull

**Comment by gene1wood** [comment]
The legendastv provider was removed in [subliminal v2.2.0](https://github.com/Diaoul/subliminal/releases/tag/2.2.0)
